version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: povestkenet-app
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - GA_ID=${GA_ID}
      - YM_ID=${YM_ID}
      - GTM_ID=${GTM_ID}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - nuxt-data:/app/.output

  nginx:
    image: nginx:alpine
    container_name: povestkenet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - nuxt-data:/usr/share/nginx/html
      - wp-content:/var/www/html
    depends_on:
      - nuxt-app
      - wordpress

  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: povestkenet-wordpress
    restart: always
    command: >
      bash -c "
        docker-entrypoint.sh apache2-foreground &
        sleep 10
        php /var/www/html/wp-content/fix-redirects.php
        tail -f /dev/null
      "
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://povestkenet.kz');
        define('WP_SITEURL', 'http://povestkenet.kz');
        define('FORCE_SSL_ADMIN', false);
        define('FORCE_SSL_LOGIN', false);
    volumes:
      - wp-content:/var/www/html
      - ./wordpress/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress/php/fix-redirects.php:/var/www/html/wp-content/fix-redirects.php
    depends_on:
      - mysql

  # MySQL для WordPress
  mysql:
    image: mysql:5.7
    container_name: povestkenet-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/data:/var/lib/mysql

volumes:
  nuxt-data:
  wp-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/git-repos/work/povestkenet/wordpress/data 