version: '3.8'

services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: povestkenet-app
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - nuxt-data:/app/.output

  nginx:
    image: nginx:alpine
    container_name: povestkenet-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - nuxt-data:/usr/share/nginx/html
      - wp-content:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nuxt-app
      - wordpress

  # Certbot для SSL сертификатов
  certbot:
    image: certbot/certbot
    container_name: povestkenet-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; sleep 12h & wait $${!}; exit 0'"
    restart: always

  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: povestkenet-wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wp-content:/var/www/html
      - ./wordpress/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - mysql

  # MySQL для WordPress
  mysql:
    image: mysql:5.7
    container_name: povestkenet-mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/data:/var/lib/mysql

volumes:
  nuxt-data:
  wp-content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/git-repos/work/povestkenet/wordpress/data 